import { Router } from "express";
import { sendCode, signIn, studentSignUp, userSignUp } from "./auth.controller.js";
import { auth } from "../../middleWare/auth.js";
import { role } from "../../services/role.js";
import { validation } from "../../middleWare/validation.js";
import { signInValidation, signupValidation } from "./auth.validation.js";
const router = Router();
router.post("/registerUser",validation(signupValidation),auth([role.admin]), userSignUp);
router.post("/registerStudent",auth([role.admin]), studentSignUp);
router.post("/signIn",validation(signInValidation), signIn);
router.post("/sendCode", sendCode);
export default router;
